UPDATE TPAKET SET BRANCHPOOL = '760';
UPDATE TDELIVERY SET BRANCHPOOL = '760';
UPDATE MBRANCH SET BRANCHLEVEL = 1 WHERE BRANCHID > '699';
UPDATE MBRANCH SET BRANCHLEVEL = 2 WHERE BRANCHID BETWEEN '600' AND '699';
UPDATE MBRANCH SET BRANCHLEVEL = 3 WHERE BRANCHID BETWEEN '001' AND '321';